name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avz --delete --exclude='.git'
          path: ./
          remote_path: /var/www/aiforge/
          remote_host: 31.220.60.140
          remote_user: root
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
